<?php

declare(strict_types=1);

namespace tests\Schema;

use arabcoders\database\Schema\Definition\ColumnDefinition;
use arabcoders\database\Schema\Definition\ColumnType;
use arabcoders\database\Schema\Definition\ForeignKeyDefinition;
use arabcoders\database\Schema\Definition\IndexDefinition;
use arabcoders\database\Schema\Definition\TableDefinition;
use arabcoders\database\Schema\Dialect\PostgresDialect;
use PHPUnit\Framework\TestCase;
use RuntimeException;

final class PostgresDialectTest extends TestCase
{
    public function testPostgresDialectGeneratesSql(): void
    {
        $table = new TableDefinition('widgets');
        $table->addColumn(new ColumnDefinition('id', ColumnType::Int, autoIncrement: true));
        $table->addColumn(new ColumnDefinition('name', ColumnType::VarChar, length: 255, nullable: false, hasDefault: true, default: ''));
        $table->addColumn(new ColumnDefinition('active', ColumnType::Boolean, hasDefault: true, default: true));
        $table->addColumn(new ColumnDefinition('payload', ColumnType::Json, nullable: true));
        $table->addColumn(new ColumnDefinition('user_id', ColumnType::Int, nullable: false));
        $table->addColumn(new ColumnDefinition('alt_id', ColumnType::Int, length: 11));
        $table->setPrimaryKey(['id']);

        $table->addIndex(new IndexDefinition('idx_widgets_name', ['name'], unique: false, type: 'index', algorithm: ['pgsql' => 'btree']));
        $table->addForeignKey(new ForeignKeyDefinition('fk_widgets_user', ['user_id'], 'users', ['id'], 'cascade', 'restrict'));

        $dialect = new PostgresDialect();

        $createSql = $dialect->createTableSql($table);
        static::assertStringContainsString('CREATE TABLE "widgets"', $createSql);
        static::assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $createSql);
        static::assertStringContainsString('DEFAULT TRUE', $createSql);
        static::assertStringContainsString('jsonb', $createSql);
        static::assertStringContainsString('PRIMARY KEY ("id")', $createSql);
        static::assertStringContainsString('FOREIGN KEY ("user_id")', $createSql);
        static::assertStringNotContainsString('integer(11)', $createSql);
        static::assertStringNotContainsString('COLLATE utf8mb4_bin', $createSql);

        $nameColumn = $table->getColumn('name');
        static::assertNotNull($nameColumn);
        static::assertStringContainsString('ALTER TABLE "widgets" ADD COLUMN', $dialect->addColumnSql('widgets', $nameColumn));

        $alterSql = $dialect->alterColumnSql('widgets', $nameColumn);
        static::assertStringContainsString('ALTER COLUMN "name" TYPE varchar(255)', $alterSql);
        static::assertStringContainsString('ALTER COLUMN "name" SET NOT NULL', $alterSql);
        static::assertStringContainsString('ALTER COLUMN "name" SET DEFAULT', $alterSql);

        static::assertStringContainsString('DROP COLUMN "name"', $dialect->dropColumnSql('widgets', 'name'));

        $index = $table->getIndex('idx_widgets_name');
        static::assertNotNull($index);
        static::assertStringContainsString('CREATE INDEX', $dialect->addIndexSql('widgets', $index));
        static::assertStringContainsString('USING BTREE', $dialect->addIndexSql('widgets', $index));
        static::assertStringContainsString('DROP INDEX IF EXISTS', $dialect->dropIndexSql('widgets', $index));

        $fulltextIndex = new IndexDefinition('idx_widgets_fulltext', ['name', 'payload'], unique: false, type: 'fulltext');
        $fulltextSql = $dialect->addIndexSql('widgets', $fulltextIndex);
        static::assertStringContainsString('USING GIN', $fulltextSql);
        static::assertStringContainsString("to_tsvector('english'", $fulltextSql);

        $foreignKey = $table->getForeignKey('fk_widgets_user');
        static::assertNotNull($foreignKey);
        static::assertStringContainsString('ADD CONSTRAINT "fk_widgets_user"', $dialect->addForeignKeySql('widgets', $foreignKey));
        static::assertStringContainsString('DROP CONSTRAINT "fk_widgets_user"', $dialect->dropForeignKeySql('widgets', $foreignKey));

        static::assertStringContainsString('ADD PRIMARY KEY', $dialect->addPrimaryKeySql('widgets', ['id']));
        static::assertStringContainsString('DROP CONSTRAINT', $dialect->dropPrimaryKeySql('widgets'));

        static::assertStringContainsString('RENAME TO', $dialect->renameTableSql('old_widgets', 'widgets'));
        static::assertStringContainsString('RENAME COLUMN', $dialect->renameColumnSql('widgets', 'fieldFoo', 'field_foo'));

        static::assertTrue($dialect->supportsAlterColumn());
        static::assertTrue($dialect->supportsDropColumn());
        static::assertTrue($dialect->supportsForeignKeys());
        static::assertTrue($dialect->supportsPrimaryKeyAlter());
    }

    public function testUniqueIndexWithHashAlgorithmFallsBackToBtree(): void
    {
        $dialect = new PostgresDialect();

        // PostgreSQL does not support UNIQUE on hash indexes
        // Should silently fall back to btree
        $uniqueHashIndex = new IndexDefinition(
            'uniq_test_hash',
            ['email'],
            unique: true,
            type: 'index',
            algorithm: ['pgsql' => 'hash'],
        );

        $sql = $dialect->addIndexSql('users', $uniqueHashIndex);
        static::assertIsString($sql);
        static::assertStringContainsString('CREATE UNIQUE INDEX', $sql);
        static::assertStringContainsString('USING BTREE', $sql);
        static::assertStringNotContainsString('USING HASH', $sql);
    }

    public function testUniqueIndexWithBtreeAlgorithmWorksNormally(): void
    {
        $dialect = new PostgresDialect();

        $uniqueBtreeIndex = new IndexDefinition(
            'uniq_test_btree',
            ['username'],
            unique: true,
            type: 'index',
            algorithm: ['pgsql' => 'btree'],
        );

        $sql = $dialect->addIndexSql('users', $uniqueBtreeIndex);
        static::assertIsString($sql);
        static::assertStringContainsString('CREATE UNIQUE INDEX', $sql);
        static::assertStringContainsString('USING BTREE', $sql);
    }

    public function testNonUniqueIndexWithHashAlgorithmWorks(): void
    {
        $dialect = new PostgresDialect();

        $hashIndex = new IndexDefinition(
            'idx_test_hash',
            ['email'],
            unique: false,
            type: 'index',
            algorithm: ['pgsql' => 'hash'],
        );

        $sql = $dialect->addIndexSql('users', $hashIndex);
        static::assertIsString($sql);
        static::assertStringContainsString('CREATE INDEX', $sql);
        static::assertStringContainsString('USING HASH', $sql);
        static::assertStringNotContainsString('UNIQUE', $sql);
    }

    public function testDropIndexSqlReturnsString(): void
    {
        $dialect = new PostgresDialect();

        $index = new IndexDefinition(
            'idx_users_email',
            ['email'],
            unique: false,
            type: 'index',
        );

        $sql = $dialect->dropIndexSql('users', $index);
        static::assertIsString($sql);
        static::assertStringContainsString('DROP INDEX IF EXISTS', $sql);
        static::assertStringContainsString('"idx_users_email"', $sql);
    }

    public function testPostgresDialectSupportsPartialAndExpressionIndexes(): void
    {
        $dialect = new PostgresDialect();

        $index = new IndexDefinition(
            name: 'idx_users_lower_email',
            columns: [],
            expression: '(lower(email))',
            where: 'deleted_at IS NULL',
        );

        $sql = $dialect->addIndexSql('users', $index);
        static::assertStringContainsString('CREATE INDEX', $sql);
        static::assertStringContainsString('((lower(email)))', $sql);
        static::assertStringContainsString('WHERE deleted_at IS NULL', $sql);
    }

    public function testPostgresDialectUsesProvidedNameForExpressionIndexes(): void
    {
        $dialect = new PostgresDialect();
        $index = new IndexDefinition(
            name: 'idx_users_lower_email_custom',
            columns: [],
            expression: '(lower(email))',
        );

        $sql = $dialect->addIndexSql('users', $index);
        static::assertStringContainsString('"idx_users_lower_email_custom"', $sql);
    }

    public function testPostgresDialectRejectsVirtualGeneratedColumn(): void
    {
        $table = new TableDefinition('widgets');
        $table->addColumn(new ColumnDefinition(
            name: 'computed',
            type: ColumnType::Int,
            generated: true,
            generatedExpression: 'base + 1',
            generatedStored: false,
        ));

        $this->expectException(RuntimeException::class);
        (new PostgresDialect())->createTableSql($table);
    }
}
