<?php

declare(strict_types=1);

namespace tests\Schema;

use arabcoders\database\Schema\Definition\ColumnDefinition;
use arabcoders\database\Schema\Definition\ColumnType;
use arabcoders\database\Schema\Definition\ForeignKeyDefinition;
use arabcoders\database\Schema\Definition\IndexDefinition;
use arabcoders\database\Schema\Definition\TableDefinition;
use arabcoders\database\Schema\Dialect\PostgresDialect;
use RuntimeException;
use tests\TestCase;

final class PostgresDialectTest extends TestCase
{
    public function testGeneratesSql(): void
    {
        $table = new TableDefinition('widgets');
        $table->addColumn(new ColumnDefinition('id', ColumnType::Int, autoIncrement: true));
        $table->addColumn(new ColumnDefinition('name', ColumnType::VarChar, length: 255, nullable: false, hasDefault: true, default: ''));
        $table->addColumn(new ColumnDefinition('active', ColumnType::Boolean, hasDefault: true, default: true));
        $table->addColumn(new ColumnDefinition('payload', ColumnType::Json, nullable: true));
        $table->addColumn(new ColumnDefinition('user_id', ColumnType::Int, nullable: false));
        $table->addColumn(new ColumnDefinition('alt_id', ColumnType::Int, length: 11));
        $table->setPrimaryKey(['id']);

        $table->addIndex(new IndexDefinition('idx_widgets_name', ['name'], unique: false, type: 'index', algorithm: ['pgsql' => 'btree']));
        $table->addForeignKey(new ForeignKeyDefinition('fk_widgets_user', ['user_id'], 'users', ['id'], 'cascade', 'restrict'));

        $dialect = new PostgresDialect();

        $createSql = $dialect->createTableSql($table);
        static::assertSame(
            "CREATE TABLE \"widgets\" (\n"
            . "    \"id\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n"
            . "    \"name\" varchar(255) NOT NULL DEFAULT '',\n"
            . "    \"active\" boolean NOT NULL DEFAULT TRUE,\n"
            . "    \"payload\" jsonb NULL,\n"
            . "    \"user_id\" integer NOT NULL,\n"
            . "    \"alt_id\" integer NOT NULL,\n"
            . "    PRIMARY KEY (\"id\"),\n"
            . "    CONSTRAINT \"fk_widgets_user\" FOREIGN KEY (\"user_id\") REFERENCES \"users\" (\"id\") ON DELETE CASCADE ON UPDATE RESTRICT\n"
            . ')',
            $createSql,
        );

        $nameColumn = $table->getColumn('name');
        static::assertNotNull($nameColumn);
        static::assertSame(
            'ALTER TABLE "widgets" ADD COLUMN "name" varchar(255) NOT NULL DEFAULT \'\'',
            $dialect->addColumnSql('widgets', $nameColumn),
        );

        $alterSql = $dialect->alterColumnSql('widgets', $nameColumn);
        static::assertSame(
            'ALTER TABLE "widgets" ALTER COLUMN "name" TYPE varchar(255), ALTER COLUMN "name" SET NOT NULL, ALTER COLUMN "name" SET DEFAULT \'\'',
            $alterSql,
        );

        static::assertSame('ALTER TABLE "widgets" DROP COLUMN "name"', $dialect->dropColumnSql('widgets', 'name'));

        $index = $table->getIndex('idx_widgets_name');
        static::assertNotNull($index);
        static::assertSame('CREATE INDEX "idx_widgets_name" ON "widgets" USING BTREE ("name")', $dialect->addIndexSql('widgets', $index));
        static::assertSame('DROP INDEX IF EXISTS "idx_widgets_name"', $dialect->dropIndexSql('widgets', $index));

        $fulltextIndex = new IndexDefinition('idx_widgets_fulltext', ['name', 'payload'], unique: false, type: 'fulltext');
        $fulltextSql = $dialect->addIndexSql('widgets', $fulltextIndex);
        static::assertSame(
            'CREATE INDEX "idx_widgets_fulltext" ON "widgets" USING GIN ((to_tsvector(\'english\', "name") || to_tsvector(\'english\', "payload")))',
            $fulltextSql,
        );

        $foreignKey = $table->getForeignKey('fk_widgets_user');
        static::assertNotNull($foreignKey);
        static::assertSame(
            'ALTER TABLE "widgets" ADD CONSTRAINT "fk_widgets_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT',
            $dialect->addForeignKeySql('widgets', $foreignKey),
        );
        static::assertSame('ALTER TABLE "widgets" DROP CONSTRAINT "fk_widgets_user"', $dialect->dropForeignKeySql('widgets', $foreignKey));

        static::assertSame('ALTER TABLE "widgets" ADD PRIMARY KEY ("id")', $dialect->addPrimaryKeySql('widgets', ['id']));
        static::assertSame('ALTER TABLE "widgets" DROP CONSTRAINT "widgets_pkey"', $dialect->dropPrimaryKeySql('widgets'));

        static::assertSame('ALTER TABLE "old_widgets" RENAME TO "widgets"', $dialect->renameTableSql('old_widgets', 'widgets'));
        static::assertSame('ALTER TABLE "widgets" RENAME COLUMN "fieldFoo" TO "field_foo"', $dialect->renameColumnSql(
            'widgets',
            'fieldFoo',
            'field_foo',
        ));

        static::assertTrue($dialect->supportsAlterColumn());
        static::assertTrue($dialect->supportsDropColumn());
        static::assertTrue($dialect->supportsForeignKeys());
        static::assertTrue($dialect->supportsPrimaryKeyAlter());
    }

    public function testUniqueHashBtree(): void
    {
        $dialect = new PostgresDialect();

        $uniqueHashIndex = new IndexDefinition(
            'uniq_test_hash',
            ['email'],
            unique: true,
            type: 'index',
            algorithm: ['pgsql' => 'hash'],
        );

        $sql = $dialect->addIndexSql('users', $uniqueHashIndex);
        static::assertSame('CREATE UNIQUE INDEX "uniq_test_hash" ON "users" USING BTREE ("email")', $sql);
    }

    public function testUniqueBtreeIndex(): void
    {
        $dialect = new PostgresDialect();

        $uniqueBtreeIndex = new IndexDefinition(
            'uniq_test_btree',
            ['username'],
            unique: true,
            type: 'index',
            algorithm: ['pgsql' => 'btree'],
        );

        $sql = $dialect->addIndexSql('users', $uniqueBtreeIndex);
        static::assertSame('CREATE UNIQUE INDEX "uniq_test_btree" ON "users" USING BTREE ("username")', $sql);
    }

    public function testNonUniqueIndex(): void
    {
        $dialect = new PostgresDialect();

        $hashIndex = new IndexDefinition(
            'idx_test_hash',
            ['email'],
            unique: false,
            type: 'index',
            algorithm: ['pgsql' => 'hash'],
        );

        $sql = $dialect->addIndexSql('users', $hashIndex);
        static::assertSame('CREATE INDEX "idx_test_hash" ON "users" USING HASH ("email")', $sql);
    }

    public function testDropIndexSql(): void
    {
        $dialect = new PostgresDialect();

        $index = new IndexDefinition(
            'idx_users_email',
            ['email'],
            unique: false,
            type: 'index',
        );

        $sql = $dialect->dropIndexSql('users', $index);
        static::assertSame('DROP INDEX IF EXISTS "idx_users_email"', $sql);
    }

    public function testSupportsPartialExpression(): void
    {
        $dialect = new PostgresDialect();

        $index = new IndexDefinition(
            name: 'idx_users_lower_email',
            columns: [],
            expression: '(lower(email))',
            where: 'deleted_at IS NULL',
        );

        $sql = $dialect->addIndexSql('users', $index);
        static::assertSame('CREATE INDEX "idx_users_lower_email" ON "users" USING BTREE ((lower(email))) WHERE deleted_at IS NULL', $sql);
    }

    public function testKeepsExpressionIndex(): void
    {
        $dialect = new PostgresDialect();
        $index = new IndexDefinition(
            name: 'idx_users_lower_email_custom',
            columns: [],
            expression: '(lower(email))',
        );

        $sql = $dialect->addIndexSql('users', $index);
        static::assertSame('CREATE INDEX "idx_users_lower_email_custom" ON "users" USING BTREE ((lower(email)))', $sql);
    }

    public function testRejectsVirtualGenerated(): void
    {
        $table = new TableDefinition('widgets');
        $table->addColumn(new ColumnDefinition(
            name: 'computed',
            type: ColumnType::Int,
            generated: true,
            generatedExpression: 'base + 1',
            generatedStored: false,
        ));

        $this->expectException(RuntimeException::class);
        new PostgresDialect()->createTableSql($table);
    }
}
